insert into products (id, name, price, categories_id) values (1, 'Orbexilum Raf.', 685, true);
insert into products (id, name, price, categories_id) values (2, 'Penstemon acuminatus Douglas ex Lindl. var. latebracteatus N.H. Holmgren', 1622, true);
insert into products (id, name, price, categories_id) values (3, 'Aplectrum Torr.', 2319, true);
insert into products (id, name, price, categories_id) values (4, 'Sedum nanifolium Fröd.', 318, true);
insert into products (id, name, price, categories_id) values (5, 'Schiedeella Schltr.', 511, true);
insert into products (id, name, price, categories_id) values (6, 'Blechnum chordatum (Desv.) Hieron.', 1823, false);
insert into products (id, name, price, categories_id) values (7, 'Asclepias arenaria Torr.', 2396, false);
insert into products (id, name, price, categories_id) values (8, 'Caloplaca herbidella (Hue) H. Magn.', 2485, false);
insert into products (id, name, price, categories_id) values (9, 'Cydista Miers', 2752, false);
insert into products (id, name, price, categories_id) values (10, 'Glossopetalon texense (Ensign) H. St. John', 2899, false);
insert into products (id, name, price, categories_id) values (11, 'Osmunda cinnamomea L. var. cinnamomea', 1416, false);
insert into products (id, name, price, categories_id) values (12, 'Juniperus monosperma (Engelm.) Sarg. var. monosperma', 2462, false);
insert into products (id, name, price, categories_id) values (13, 'Silene stellata (L.) W.T. Aiton', 1428, false);
insert into products (id, name, price, categories_id) values (14, 'Cuscuta suaveolens Ser.', 1961, false);
insert into products (id, name, price, categories_id) values (15, 'Andropogon brachystachyus Chapm.', 989, false);
insert into products (id, name, price, categories_id) values (16, 'Exochorda racemosa (Lindl.) Rehder', 354, false);
insert into products (id, name, price, categories_id) values (17, 'Calypso bulbosa (L.) Oakes var. americana (R. Br.) Luer', 213, false);
insert into products (id, name, price, categories_id) values (18, 'Juncus tiehmii Ertter', 1482, false);
insert into products (id, name, price, categories_id) values (19, 'Erigeron lanatus Hook.', 2425, false);
insert into products (id, name, price, categories_id) values (20, 'Juncus subcaudatus (Engelm.) Coville & S.F. Blake var. subcaudatus', 1351, false);
